**Numerical Python** (NumPy)
is used for numerical operations related to Linear algebra and calculus. 

# Understanding Dimensionality


* 1-dimensional space
<img src='https://i.stack.imgur.com/LGBAG.png' height = 400>

* 2-dimensional space
<img src='https://raw.githubusercontent.com/rweigel/computingforscientists/master/Plotting_1D/figures/Plotting_1D_III.py.png' height = 400>

* 3-dimensional space
<img src='https://www.mathworks.com/help/examples/matlab/win64/Creating3DPlotsExample_02.png' height = 400>



In [ ]:
import numpy as np

In [ ]:
l = [1,2,3]

x1 = np.array(l)
print(type(x1), x1)

<class 'numpy.ndarray'> [1 2 3]


In [ ]:
print("Dimensionality of the numpy array:", x1.ndim)
print("Shape of the numpy array:", x1.shape)

Dimensionality of the numpy array: 1
Shape of the numpy array: (3,)


In [ ]:
x2 = np.array([[1], [2], [3]])
# [ [1] ,[2] ,[3]  ]
print(x2)
print("Dimensionality of the numpy array:", x2.ndim)
print("Shape of the numpy array:", x2.shape)

[[1]
 [2]
 [3]]
Dimensionality of the numpy array: 2
Shape of the numpy array: (3, 1)


In [ ]:
import numpy as np
x2 = np.array([[10, 9, 8], [7, 6, 5], [4, 3, 2]])

resized_matrix = np.resize(x2, (6,2))
print(resized_matrix)
print(x2)
print("Dimensionality of the numpy array:", x2.ndim)
print("Shape of the numpy array:", x2.shape)
print("Dimensionality of the numpy array:", resized_matrix.ndim)
print("Shape of the numpy array:", resized_matrix.shape)

[[10  9]
 [ 8  7]
 [ 6  5]
 [ 4  3]
 [ 2 10]
 [ 9  8]]
[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]
Dimensionality of the numpy array: 2
Shape of the numpy array: (3, 3)
Dimensionality of the numpy array: 2
Shape of the numpy array: (6, 2)


In [ ]:
x3 = np.array([[[ 1,2, 10], [3, 4, 20]], [[5, 6, 30], [ 7,8, 40]]])
#[[[ 1,2, 10], [3, 4, 20]], [[5, 6, 30], [ 7,8, 40]]])

print(x3)
print("Dimensionality of the numpy array:", x3.ndim)
print("Shape of the numpy array:", x3.shape)

[[[ 1  2 10]
  [ 3  4 20]]

 [[ 5  6 30]
  [ 7  8 40]]]
Dimensionality of the numpy array: 3
Shape of the numpy array: (2, 2, 3)


# Using NumPy arrays to hold datasets for your Machine Learning task

![alt text](https://miro.medium.com/max/1828/1*CBtaBQIg5aypyK3F4nIkWQ.png)

In [ ]:
dataset_ftrs = np.array([
                         [800, 0, 0.3048, 71.3, 0.00266337], 
                         [1000, 0, 0.3048, 71.3, 0.00266337], 
                         [1250, 0, 0.3048, 71.3, 0.00266337], 
                         [1600, 0, 0.3048, 71.3, 0.00266337], 
                         [2000, 0, 0.3048, 71.3, 0.00266337], 
                         [2500, 0, 0.3048, 71.3, 0.00266337], 
                         [3150, 0, 0.3048, 71.3, 0.00266337], 
                         [4000, 0, 0.3048, 71.3, 0.00266337], 
                         [5000, 0, 0.3048, 71.3, 0.00266337], 
                         [6300, 0, 0.3048, 71.3, 0.00266337], 
                         [8000, 0, 0.3048, 71.3, 0.00266337], 
])

dataset_labels = np.array([
                           [126.201],
                           [125.201],
                           [125.951],
                           [127.591],
                           [127.461],
                           [125.571],
                           [125.201],
                           [123.061],
                           [121.301],
                           [119.541],
                           [117.151],
])

# Each row => Data Item
# Each column => Data feature

print(dataset_ftrs)
print(dataset_labels)

print("Dimensionality of dataset's features:", dataset_ftrs.ndim)
print("Shape of dataset's features:", dataset_ftrs.shape)

print("Dimensionality of dataset's labels:", dataset_labels.ndim)
print("Shape of dataset's labels:", dataset_labels.shape)

[[8.00000e+02 0.00000e+00 3.04800e-01 7.13000e+01 2.66337e-03]
 [1.00000e+03 0.00000e+00 3.04800e-01 7.13000e+01 2.66337e-03]
 [1.25000e+03 0.00000e+00 3.04800e-01 7.13000e+01 2.66337e-03]
 [1.60000e+03 0.00000e+00 3.04800e-01 7.13000e+01 2.66337e-03]
 [2.00000e+03 0.00000e+00 3.04800e-01 7.13000e+01 2.66337e-03]
 [2.50000e+03 0.00000e+00 3.04800e-01 7.13000e+01 2.66337e-03]
 [3.15000e+03 0.00000e+00 3.04800e-01 7.13000e+01 2.66337e-03]
 [4.00000e+03 0.00000e+00 3.04800e-01 7.13000e+01 2.66337e-03]
 [5.00000e+03 0.00000e+00 3.04800e-01 7.13000e+01 2.66337e-03]
 [6.30000e+03 0.00000e+00 3.04800e-01 7.13000e+01 2.66337e-03]
 [8.00000e+03 0.00000e+00 3.04800e-01 7.13000e+01 2.66337e-03]]
[[126.201]
 [125.201]
 [125.951]
 [127.591]
 [127.461]
 [125.571]
 [125.201]
 [123.061]
 [121.301]
 [119.541]
 [117.151]]
Dimensionality of dataset's features: 2
Shape of dataset's features: (11, 5)
Dimensionality of dataset's labels: 2
Shape of dataset's labels: (11, 1)


# Operations on NumPy arrays

In [ ]:
A = np.array([[10, 9, 8], [7, 6, 5], [4, 3, 2]])
B = np.array([[11,22,33], [54, 12, 10], [5, 4 ,9]])

print(A)
print()
print(B)

[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]

[[11 22 33]
 [54 12 10]
 [ 5  4  9]]


In [ ]:
print(A + B) # Addition

[[21 31 41]
 [61 18 15]
 [ 9  7 11]]


In [ ]:
print(A - B) # Subtraction

[[ -1 -13 -25]
 [-47  -6  -5]
 [ -1  -1  -7]]


In [ ]:
print(A * B) # Multiplication

[[110 198 264]
 [378  72  50]
 [ 20  12  18]]


In [ ]:
print(A / B) # Division

[[0.90909091 0.40909091 0.24242424]
 [0.12962963 0.5        0.5       ]
 [0.8        0.75       0.22222222]]


In [ ]:
print(A ^ B) # XOR 

[[ 1 31 41]
 [49 10 15]
 [ 1  7 11]]


In [ ]:
print(A @ B) # Matrix multiplication of A and B
# (3,3) @ (3,3) => {3,3}


[[636 360 492]
 [426 246 336]
 [216 132 180]]


2*3 3*2=

In [ ]:
print(A)
print()
print(A.T) # Transpose of A

[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]

[[10  7  4]
 [ 9  6  3]
 [ 8  5  2]]


In [ ]:
X = np.array([[1, 2, 3]]) # Row matrix

print(X, X.shape, '\n')

X_trans = X.T
print(X_trans, X_trans.shape) # Column matrix

[[1 2 3]] (1, 3) 

[[1]
 [2]
 [3]] (3, 1)


In [ ]:
print(A)
print()
print(A.ravel())

[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]

[10  9  8  7  6  5  4  3  2]


In [ ]:
print(A, A.shape)
print()
print(X, X.shape)
print()

vert_stacked = np.vstack((A, X, X))
print(vert_stacked)

[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]] (3, 3)

[[1 2 3]] (1, 3)

[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]
 [ 1  2  3]
 [ 1  2  3]]


In [ ]:
print(A, A.shape)
print()
print(X_trans, X_trans.shape)
print()

hrztl_stacked = np.hstack((A, X_trans))
print(hrztl_stacked)

[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]] (3, 3)

[[1]
 [2]
 [3]] (3, 1)

[[10  9  8  1]
 [ 7  6  5  2]
 [ 4  3  2  3]]


In [ ]:
print(hrztl_stacked, hrztl_stacked.shape)
print()

resized_matrix = np.resize(hrztl_stacked, (6,2))
print(resized_matrix, resized_matrix.shape)
print()

resized_matrix = np.resize(hrztl_stacked, (12, 1))
print(resized_matrix, resized_matrix.shape)

[[10  9  8  1]
 [ 7  6  5  2]
 [ 4  3  2  3]] (3, 4)

[[10  9]
 [ 8  1]
 [ 7  6]
 [ 5  2]
 [ 4  3]
 [ 2  3]] (6, 2)

[[10]
 [ 9]
 [ 8]
 [ 1]
 [ 7]
 [ 6]
 [ 5]
 [ 2]
 [ 4]
 [ 3]
 [ 2]
 [ 3]] (12, 1)


In [ ]:
print(np.linalg.det(B)) # Determinant of matrix B

-3696.0


In [ ]:
print(B)
print()

B_inv = np.linalg.inv(B)
print(B_inv)
print()

print((B_inv @ B).round(0))

[[11 22 33]
 [54 12 10]
 [ 5  4  9]]

[[-0.01839827  0.01785714  0.04761905]
 [ 0.11796537  0.01785714 -0.45238095]
 [-0.04220779 -0.01785714  0.28571429]]

[[ 1.  0.  0.]
 [-0.  1. -0.]
 [ 0.  0.  1.]]


In [ ]:
print(np.log(B), '\n')
print(np.sin(B), '\n')
print(np.tan(B), '\n')
print(np.exp(B), '\n')

[[2.39789527 3.09104245 3.49650756]
 [3.98898405 2.48490665 2.30258509]
 [1.60943791 1.38629436 2.19722458]] 

[[-0.99999021 -0.00885131  0.99991186]
 [-0.55878905 -0.53657292 -0.54402111]
 [-0.95892427 -0.7568025   0.41211849]] 

[[-2.25950846e+02  8.85165604e-03 -7.53130148e+01]
 [ 6.73800101e-01 -6.35859929e-01  6.48360827e-01]
 [-3.38051501e+00  1.15782128e+00 -4.52315659e-01]] 

[[5.98741417e+04 3.58491285e+09 2.14643580e+14]
 [2.83075330e+23 1.62754791e+05 2.20264658e+04]
 [1.48413159e+02 5.45981500e+01 8.10308393e+03]] 



In [ ]:
print(A, A.shape, '\n')

print("Sum:")
print(A.sum())
print(A.sum(axis=0)) # (0,Column)
print(A.sum(axis=1)) # (Row, 1)

print("\nMax:")
print(A.max())
print(A.max(axis=0))
print(A.max(axis=1))

print("\nMin:")
print(A.min())
print(A.min(axis=0))
print(A.min(axis=1))

[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]] (3, 3) 

Sum:
54
[21 18 15]
[27 18  9]

Max:
10
[10  9  8]
[10  7  4]

Min:
2
[4 3 2]
[8 5 2]


# Vector Products

Vectors are basically [Tensors](https://www.youtube.com/watch?v=f5liqUk0ZTw) of rank 1

In [ ]:
x1 = np.array([[1], [2], [3]]) # Column Matrix
x2 = np.array([[4, 5, 6]]) # Row Matrix

print(x1, '\n')
print(x2, '\n')
print(x1.shape, x2.shape)

[[1]
 [2]
 [3]] 

[[4 5 6]] 

(3, 1) (1, 3)


## Vector Outer product 
---

`Consider the following column matrices (or) vectors`


$\vec{X} = \begin{pmatrix} x_1\\ x_2\\ x_3 \end{pmatrix}$


$\vec{Y} = \begin{pmatrix} y_1\\ y_2\\ y_3 \end{pmatrix}$

$\vec{X} \vec{Y}^T = \begin{pmatrix} x_1\\ x_2\\ x_3 \end{pmatrix}\begin{pmatrix} y_1 & y_2 & y_3 \end{pmatrix}  = \begin{pmatrix} x_1y_1 & x_1y_2 & x_1y_3 \\ x_2y_1 & x_2y_2 & x_2y_3 \\ x_3y_1 & x_3y_2 & x_3y_3 \end{pmatrix}$

In [ ]:
# Vector Outer Product

print(x1 @ x2) # np array of shape (3, 3)
# (3, 1) @ (1, 3) = (3,3)

[36 30 24]


## Vector Inner product (or) Dot product between two vectors
---

`Consider the following column matrices (or) vectors`


$\vec{X} = \begin{pmatrix} x_1\\ x_2\\ x_3 \end{pmatrix}$


$\vec{Y} = \begin{pmatrix} y_1\\ y_2\\ y_3 \end{pmatrix}$

$\vec{X} \cdot \vec{Y} = x_1y_1 + x_2y_2  + x_3y_3$

`Formula for dot product in vector algebra` 

$\vec{X}^T \vec{Y} = \begin{pmatrix} x_1 & x_2 & x_3 \end{pmatrix}\begin{pmatrix} y_1\\ y_2\\ y_3 \end{pmatrix} $

In [ ]:
# Vector Inner Product (or) Dot product of two vectors

print(x2 @ x1) # np array of shape (1, 1)
# (1, 3) @ (3, 1)

[52 34 16]


# Broadcasting in NumPy
![alt text](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
X = np.array([[1, 1, 1]])
Y = np.array([[2], [2], [2]])

print(A, A.shape, '\n')
print(X, X.shape, '\n')
print(Y, Y.shape, '\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 

[[1 1 1]] (1, 3) 

[[2]
 [2]
 [2]] (3, 1) 



In [ ]:
print(A + 10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [ ]:
print(A + X)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
print(A + Y)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
print(X + Y)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


# Other np methods

In [ ]:
A = np.arange(10)
print(A)

print(np.resize(A, (3,3)))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
A = np.zeros((2,4))
print(A)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
A = np.ones((2,4))
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
A = np.random.random((2,2)) # 0-1
print(A)

[[0.0111457  0.70934242]
 [0.39524105 0.60398139]]


# References
*  [**What is a Tensor {important}**](https://www.youtube.com/watch?v=f5liqUk0ZTw)
*  [Video on vector products](https://www.youtube.com/watch?v=FCmH4MqbFGs)
*  [NumPy Documentation](https://numpy.org/)
*  [NumPy Tutorial by `Justin Johnson`](http://cs231n.github.io/python-numpy-tutorial/#numpy)
*  [Essence of Linear Algebra](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab)  
